src/SisGG/FinalBundle/Entity/Cliente.php
<?php

namespace SisGG\FinalBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use SisGG\FinalBundle\Validator\Constraints as MyAssert;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * @ORM\Entity(repositoryClass="SisGG\FinalBundle\Entity\ClienteRepository")
 * @ORM\InheritanceType("JOINED")
 * @ORM\DiscriminatorColumn(name="discr", type="string")
 * @ORM\HasLifecycleCallbacks()
 * @Gedmo\Loggable
 */
class Cliente implements \Serializable {

    /**
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @Assert\Valid
     * @ORM\OneToOne(targetEntity="Telefono",cascade="persist")
     * @Gedmo\Versioned 
     */
    private $telefono;

    /**
     * @ORM\OneToOne(targetEntity="Direccion",cascade={"persist"})
     * @ORM\JoinColumn(name="direccion_id", referencedColumnName="id")
     * @Gedmo\Versioned
     */
    private $direccion;

    /**
     * @ORM\Column(type="string", length=60, nullable=true)
     * @Assert\Email(message="Ingrese un email valido")
     * @Gedmo\Versioned  
     */
    private $email;

    /**
     * @ORM\OneToMany(targetEntity="Pedido",mappedBy="cliente")
     */
    private $pedidos;

    /**
     * @ORM\OneToMany(targetEntity="Venta",mappedBy="cliente")
     */
    private  $ventas;

    /**
     * @ORM\Column(type="string")
     * @Gedmo\Versioned 
     */
    private $estado;

    /**
     * @ORM\ManyToOne(targetEntity="TipoDocumento")
     * @Gedmo\Versioned 
     */
    private $tipoDocumento;

    /**
     * @ORM\Column(type="string",nullable=true)
     * @Assert\Regex(pattern="/\d/",
     *     match=true,
     *     message="El dni solo puede contener números")  
     * @Gedmo\Versioned 
     */
    private $documento;

    /**
     * @ORM\Column(type="string", length=25)
     * @Assert\NotBlank(message="Ingrese un apellido")
     * @Assert\Regex(pattern="/\d/",
     *     match=false,
     *     message="El apellido no puede contener números") 
     * @Gedmo\Versioned 
     */
    private $apellido;

    /**
     * @ORM\Column(type="string", length=25)
     * @Assert\NotBlank(message="Ingrese un nombre")
     *  @Assert\Regex(pattern="/\d/",
     *     match=false,
     *     message="El nombre no puede contener números") 
     * @Gedmo\Versioned
     */
    private $nombre;
    
    /**
     * @ORM\Column(type="string",nullable=true)
     * @Gedmo\Versioned
     */
    private $cuit;
          
    /**
     * @ORM\ManyToMany(targetEntity="DescuentoCliente",inversedBy="cliente")
     */
    private $descuentos;
    
    /**
     * @ORM\ManyToMany(targetEntity="GrupoCliente",mappedBy="clientes")
     */
    private $gruposCliente;
    
    /**
     * @ORM\ManyToOne(targetEntity="CondicionIva",inversedBy="clientes")
     * @Gedmo\Versioned
     */
    private $condicionIva;
    
    /**
     * @ORM\Column(type="boolean",nullable=true)
     */
    private $porDefecto;
    
    /**
     * @ORM\OneToOne(targetEntity="CuentaCorriente",mappedBy="cliente")
     * @Gedmo\Versioned
     */
    private $cuenta;
    
    /**
     * @return string
     */
    public function identificacion() {
        return "ninguna";
    }

    public function toArray() {
        $retorno = array('nombre'=>  "".$this,'cuit'=>  $this->getCuit(),'condicionIva'=> $this->getCondicionIva()->getId());
        return $retorno;
    }

    public function __toString() {
        return $this->apellido.', '.$this->nombre;
    }
    
    /**
     * @return string
     */
    public function serialize() {
        return serialize($this->id);
    }

    /**
     * @param string $data
     */
    public function unserialize($data) {
        $this->id = unserialize($data);
    }

    /**
     * @ORM\PrePersist
     */
    public function setCreatedValue() {
        $this->setEstado("activo");
    }
 
    
    public function getDescuentosActivos(){
        $retorno = array();
        foreach ($this->getDescuentos() as $descuento) {
            if ($descuento->getEstado() == 'activo')
                $retorno[ ] = $descuento;
        }
        foreach ($this->getGruposActivos() as $grupos) {
            foreach ($grupos->getDescuentosActivos() as $descuento) {
                if (!in_array($descuento, $retorno))
                    $retorno[ ] = $descuento;
            }
        }
        return $retorno;
    }
    
    public function getGruposActivos(){
        $retorno = array();
        foreach ($this->getGruposCliente() as $grupoCliente) {
            if ($grupoCliente->getEstado() == 'activo')
                $retorno[ ] = $grupoCliente;
        }
        return $retorno;
    }
    /**
     * Constructor
     */
    public function __construct()
    {
        $this->pedidos = new \Doctrine\Common\Collections\ArrayCollection();
        $this->ventas = new \Doctrine\Common\Collections\ArrayCollection();
        $this->descuentos = new \Doctrine\Common\Collections\ArrayCollection();
        $this->gruposCliente = new \Doctrine\Common\Collections\ArrayCollection();
    }
    
    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set email
     *
     * @param string $email
     * @return Cliente
     */
    public function setEmail($email)
    {
        $this->email = $email;
    
        return $this;
    }

    /**
     * Get email
     *
     * @return string 
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Set estado
     *
     * @param string $estado
     * @return Cliente
     */
    public function setEstado($estado)
    {
        $this->estado = $estado;
    
        return $this;
    }

    /**
     * Get estado
     *
     * @return string 
     */
    public function getEstado()
    {
        return $this->estado;
    }

    /**
     * Set documento
     *
     * @param string $documento
     * @return Cliente
     */
    public function setDocumento($documento)
    {
        $this->documento = $documento;
    
        return $this;
    }

    /**
     * Get documento
     *
     * @return string 
     */
    public function getDocumento()
    {
        return $this->documento;
    }

    /**
     * Set apellido
     *
     * @param string $apellido
     * @return Cliente
     */
    public function setApellido($apellido)
    {
        $this->apellido = $apellido;
    
        return $this;
    }

    /**
     * Get apellido
     *
     * @return string 
     */
    public function getApellido()
    {
        return $this->apellido;
    }

    /**
     * Set nombre
     *
     * @param string $nombre
     * @return Cliente
     */
    public function setNombre($nombre)
    {
        $this->nombre = $nombre;
    
        return $this;
    }

    /**
     * Get nombre
     *
     * @return string 
     */
    public function getNombre()
    {
        return $this->nombre;
    }
    
    /**
     * Set cuit
     *
     * @param string $cuit
     * @return Cliente
     */
    public function setCuit($cuit)
    {
        $this->cuit = $cuit;
    
        return $this;
    }

    /**
     * Get cuit
     *
     * @return string 
     */
    public function getCuit()
    {
        return $this->cuit;
    }

    /**
     * Set telefono
     *
     * @param \SisGG\FinalBundle\Entity\Telefono $telefono
     * @return Cliente
     */
    public function setTelefono(\SisGG\FinalBundle\Entity\Telefono $telefono = null)
    {
        $this->telefono = $telefono;
    
        return $this;
    }

    /**
     * Get telefono
     *
     * @return \SisGG\FinalBundle\Entity\Telefono 
     */
    public function getTelefono()
    {
        return $this->telefono;
    }

    /**
     * Set direccion
     *
     * @param \SisGG\FinalBundle\Entity\Direccion $direccion
     * @return Cliente
     */
    public function setDireccion(\SisGG\FinalBundle\Entity\Direccion $direccion = null)
    {
        $this->direccion = $direccion;

        return $this;
    }

    /**
     * Get direccion
     *
     * @return \SisGG\FinalBundle\Entity\Direccion 
     */
    public function getDireccion()
    {
        return $this->direccion;
    }

    /**
     * Add pedidos
     *
     * @param \SisGG\FinalBundle\Entity\Pedido $pedidos
     * @return Cliente
     */
    public function addPedido(\SisGG\FinalBundle\Entity\Pedido $pedidos)
    {
        $this->pedidos[] = $pedidos;
    
        return $this;
    }

    /**
     * Remove pedidos
     *
     * @param \SisGG\FinalBundle\Entity\Pedido $pedidos
     */
    public function removePedido(\SisGG\FinalBundle\Entity\Pedido $pedidos)
    {
        $this->pedidos->removeElement($pedidos);
    }

    /**
     * Get pedidos
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getPedidos()
    {
        return $this->pedidos;
    }

    /**
     * Add ventas
     *
     * @param \SisGG\FinalBundle\Entity\Venta $ventas
     * @return Cliente
     */
    public function addVenta(\SisGG\FinalBundle\Entity\Venta $ventas)
    {
        $this->ventas[] = $ventas;
    
        return $this;
    }

    /**
     * Remove ventas
     *
     * @param \SisGG\FinalBundle\Entity\Venta $ventas
     */
    public function removeVenta(\SisGG\FinalBundle\Entity\Venta $ventas)
    {
        $this->ventas->removeElement($ventas);
    }

    /**
     * Get ventas
     *

src/SisGG/FinalBundle/Controller/ClienteController.php
<?php

namespace SisGG\FinalBundle\Controller;

use SisGG\FinalBundle\Entity\Telefono;;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use SisGG\FinalBundle\Entity\Direccion;
use SisGG\FinalBundle\Entity\Cliente;
use SisGG\FinalBundle\Form\ClienteType;
use SisGG\FinalBundle\Model\GestorClientes;
use SisGG\FinalBundle\Entity\DescuentoCliente;
use Symfony\Component\HttpFoundation\Response;
/**
 * Description of ClienteController
 *
 * @author martin
 */
class ClienteController extends Controller {

    public function nuevoClienteAction() {
        $gestor = $this->get("gestor_autenticacion");
        if (!$gestor->isGranted($this->getUser(),  \SisGG\FinalBundle\Autenticacion\GestorAutenticacion::CLIENTE_NUEVO)){
            throw new \Symfony\Component\Security\Core\Exception\AccessDeniedException();
        }
        $cliente = new Cliente();
        $form = $this->createForm(new ClienteType(), $cliente);
        if ($this->getRequest()->getMethod() === 'POST') {
            $form->bindRequest($this->getRequest());
            if ($form->isValid()) {
                    $em = $this->getDoctrine()->getEntityManager();
                    $em->persist($cliente);
                    $em->flush();
                    return $this->redirect($this->generateUrl('clientes'));
            }
        }
        $provincias = $this->getDoctrine()->getRepository("SisGGFinalBundle:Provincia")->findAll();
        return $this->render('SisGGFinalBundle:Cliente:nuevoCliente.html.twig', array('form' => $form->createView(),'gestor_autenticacion'=>$gestor,'provincias'=>$provincias));
    }
    
    public function detallesAction(){
        $gestor = $this->get("gestor_autenticacion");
        if (!$gestor->isGranted($this->getUser(),  \SisGG\FinalBundle\Autenticacion\GestorAutenticacion::CLIENTE_EDITAR)){
            throw new \Symfony\Component\Security\Core\Exception\AccessDeniedException();
        }
        $em = $this->getDoctrine()->getEntityManager();
        $id = $this->getRequest()->get('id');
        $unCliente = $em->getRepository("SisGGFinalBundle:Cliente")->find($id);
        return $this->render('SisGGFinalBundle:Cliente:detallesCliente.html.twig', array('form' => null,'id'=>$id,'cliente'=>$unCliente,'gestor_autenticacion'=>$gestor));
    }

    public function clienteAction() {
         /*@var $unCliente Cliente*/
         $unCliente = $this->getDoctrine()->getEntityManager()->getRepository("SisGGFinalBundle:Cliente")->find($this->getRequest()->get("id"));
         $descuentos = array();
         /*@var $descuento DescuentoCliente*/
         foreach ($unCliente->getDescuentosActivos() as $descuento) {
             $descuentos[]=array("id"=>$descuento->getId(),"nombre"=>$descuento->getNombre(),"isPorcentaje"=>$descuento->getTipoPorcentaje(),"porcentaje"=>$descuento->getPorcentaje(),"importe"=>$descuento->getImporte(),"minimo"=>$descuento->getMinimo(),"maximo"=>$descuento->getMaximo());
         }
         $cliente = array("descuentos"=>$descuentos);
         return new Response(json_encode($cliente));
    }
    
    public function editarClienteAction() {
        $gestor = $this->get("gestor_autenticacion");
        if (!$gestor->isGranted($this->getUser(),  \SisGG\FinalBundle\Autenticacion\GestorAutenticacion::CLIENTE_EDITAR)){
            throw new \Symfony\Component\Security\Core\Exception\AccessDeniedException();
        }
        $em = $this->getDoctrine()->getEntityManager();
        $unCliente = $em->getRepository("SisGGFinalBundle:Cliente")->find($this->getRequest()->get("id"));
        $form = $this->createForm(new ClienteType(), $unCliente);
        if ($this->getRequest()->getMethod() === 'POST') {
            $form->bindRequest($this->getRequest());
            if ($form->isValid()) {
                $em->flush();
                return $this->redirect($this->generateUrl('clientes'));
            }
        }
        $provincias = $this->getDoctrine()->getRepository("SisGGFinalBundle:Provincia")->findAll();
        return $this->render('SisGGFinalBundle:Cliente:editarCliente.html.twig', array('form' => $form->createView(),'id'=>$this->getRequest()->get("id"),'gestor_autenticacion'=>$gestor,'provincias'=>$provincias));
    }

    public function borrarClienteAction() {
        $gestor = $this->get("gestor_autenticacion");
        if (!$gestor->isGranted($this->getUser(),  \SisGG\FinalBundle\Autenticacion\GestorAutenticacion::CLIENTE_BORRAR)){
            throw new \Symfony\Component\Security\Core\Exception\AccessDeniedException();
        }
        $repositorio = $this->getDoctrine()->getRepository('SisGGFinalBundle:Cliente');
        $cliente = $repositorio->find($this->getRequest()->get('id'));
        $cliente->setEstado('inactivo');
        $this->getDoctrine()->getEntityManager()->flush($cliente);
        return $this->redirect($this->generateUrl("clientes"));
    }
    
    public function activarClienteAction() {
        $gestor = $this->get("gestor_autenticacion");
        if (!$gestor->isGranted($this->getUser(),  \SisGG\FinalBundle\Autenticacion\GestorAutenticacion::CLIENTE_BORRAR)){
            throw new \Symfony\Component\Security\Core\Exception\AccessDeniedException();
        }
        $repositorio = $this->getDoctrine()->getRepository('SisGGFinalBundle:Cliente');
        $cliente = $repositorio->find($this->getRequest()->get('id'));
        $cliente->setEstado('activo');
        $this->getDoctrine()->getEntityManager()->flush($cliente);
        return $this->redirect($this->generateUrl("clientes"));
    }
    
    
    public function clientesAction() {
        $gestor = $this->get("gestor_autenticacion");
        if (!$gestor->isGranted($this->getUser(),  \SisGG\FinalBundle\Autenticacion\GestorAutenticacion::CLIENTE_LISTAR)){
            throw new \Symfony\Component\Security\Core\Exception\AccessDeniedException();
        }
        $repositorio = $this->getDoctrine()->getRepository('SisGGFinalBundle:Cliente');
        $clientes = $repositorio->findAll();
        $estado = $this->getRequest()->get('estado');
        return $this->render('SisGGFinalBundle:Cliente:clientes.html.twig', array('form' => null, 'clientes' => $clientes,'gestor_autenticacion'=>$gestor,'estado'=>$estado));
    }
    
    public function pordefectoClienteAction(){
        $gestor = $this->get("gestor_autenticacion");
        if (!$gestor->isGranted($this->getUser(),  \SisGG\FinalBundle\Autenticacion\GestorAutenticacion::CLIENTE_BORRAR)){
            throw new \Symfony\Component\Security\Core\Exception\AccessDeniedException();
        }
        $repositorio = $this->getDoctrine()->getRepository('SisGGFinalBundle:Cliente');
        $clientes = $repositorio->findAll();
        /*@var $cliente Cliente*/
        foreach ($clientes as $cliente) {
            $cliente->setPorDefecto($cliente->getId()==$this->getRequest()->get('id')?true:false);
        }
        $this->getDoctrine()->getEntityManager()->flush();
        return new Response(json_encode(array()));
    }

}

src/SisGG/FinalBundle/Resources/views/Cliente/clientes.html.twig
{% extends app.request.isXmlHttpRequest ? "::ajax.html.twig" : "SisGGFinalBundle:Cajero:cajero.html.twig" %}
{%block css%}
{{parent()}}
<style type="text/css">
        .active{
            font-weight: bold;
        }
        .estrella {
            font-family: FontAwesome;
            content: "\f006";
            padding-right: 5px;
            color: gray;
            direction: rtl;
            font-size: 30px;
        }
        .estrella:hover{
            color: gold;
            cursor: pointer;
        }
        .estrella.active{
            color: gold;
            content: "\2605";
            font-weight: bolder;
        }
</style>        
{%endblock%}
{%block ruta%}
<li>
    <a href="#">Inicio</a> <span class="divider">/</span>
</li>
<li>
    <a href="#">Clientes</a>
</li>
{%endblock%}
{% block content %}
<div class="row-fluid">
    <div class="box span12">
        <div class="box-content">
            {% set activos = 0%}
            {% set inactivos = 0%}    
            {% for cliente in clientes%}
                {%if cliente.estado=='activo'%}
                    {% set activos = activos+1%}
                {% elseif cliente.estado=='inactivo'%}
                    {% set inactivos = inactivos+1%}
                {% endif %}
            {% endfor %}     
            <legend>Clientes 
                <div class="btn-group" style='float:right;'>
                    <a title="Nuevo Cliente" href="{{path('nuevo_cliente')}}" class="btn"><i class="fa-icon-plus-sign"></i></a>
                    <a class="btn"><i class="icon-print"></i></a>
                </div>
                <small class='filtros'>
                    <ul class="nav nav-pills" id="myTab1">
                    <li class='filtro {%if (estado=='activo') or (estado==null)%}active{%endif%}'><a href='{{path('clientes')}}' >Activos({{activos}})</a></li>
                    <li class='filtro {%if estado=='inactivo'%}active{%endif%}'><a href='{{path('clientes')}}?estado=inactivo' >Inactivos({{inactivos}})</a></li> 
                    <li class='filtro {%if estado=='todos'%}active{%endif%}' ><a href='{{path('clientes')}}?estado=todos' >Todos({{activos+inactivos}})</a></li>
                    </ul>
                </small>                
            </legend>
            <table class="table table-striped table-bordered" id="clientes">
                <thead class="header">
                    <tr>
                        <th>Cliente</th>
                        <th>Teléfono</th>
                        <th>Dirección</th>
                        <th>Descuentos</th>
                        <th>Grupos</th>
                        <th>Estado</th>
                        <th>Def. Ventas</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                {%if estado==null%}
                        {%set estado='activo'%}        
                {% endif %}        
                {% for cliente in clientes%}
                     {%if estado=='todos' or cliente.estado==estado%}   
                        <tr>
                            <td>{{cliente}}</td>
                            <td>{{cliente.telefono}}</td>
                            <td>{{cliente.direccion}}</td>
                            <td style='text-align: right'>{{cliente.descuentosActivos|length}}</td>
                            <td style='text-align: right'>{{cliente.gruposActivos|length}}</td>
                            <td class='estado' style='text-align: center;'>{%if cliente.estado=='activo'%}<span class="label label-success">Activo</span>{%elseif cliente.estado=='inactivo'%}<span class="label label-important">Inactivo</span>{%endif%}</td>
                            <td style='text-align: center;'>
                                {%if cliente.porDefecto%}<span data-id='{{cliente.id}}' class='estrella active'>★</span>{%else%}<span data-id='{{cliente.id}}' class='estrella'>☆</span>{%endif%}
                            </td>
                            <td style='text-align: center;'>
                            {%if cliente.estado=='activo'%}
                                {% if gestor_autenticacion.isGranted(app.user,'cliente_editar') %}
                                   <a rel="tooltip" title="Editar" href="{{path('editar_cliente')}}?id={{cliente.id}}"><i class="fa-icon-edit"></i></a>
                                {%endif%}
                                {% if gestor_autenticacion.isGranted(app.user,'cliente_borrar') %}
                                    <a class='borrar' href='#' rel="tooltip" title="Pasar a Inactivo" data-cliente='{{cliente}}' data-id='{{cliente.id}}'><i class="fa-icon-trash"></i></a>
                                {%endif%}    
                            {%else%}
                                <a rel="tooltip" title="Pasar a Activo" href="{{path('activar_cliente')}}?id={{cliente.id}}"><i class="fa-icon-plus-sign"></i></a>
                            {% endif %}
                                <a rel="tooltip" title="Detalles" href="{{path('detalles_cliente')}}?id={{cliente.id}}"><i class="fa-icon-list-alt"></i></a>    
                            </td>
                        </tr>
                     {% endif %}       
                {% endfor %}       
                    </tbody>
                </table>    
            </div>
        </div><!--/span-->
    </div><!--/row-->
{% endblock %}
{%block modal%}
        {{parent()}}
                <div class="modal hide fade" id="eliminarCliente">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">×</button>
                        <h3>Atención!!!</h3>
                    </div>
                    <div id="dataEliminar" class="modal-body">
                        ¿Esta seguro que desea pasar el cliente <span id='cliente' style='font: bold cursive;'></span> a estado Inactivo?
                    </div>
                    <div class="modal-footer">
                        <a href="#" class="btn" data-dismiss="modal">Cancelar</a>
                        <a class="btn btn-primary" id='borrar'>Confirmar</a>
                    </div>
                </div>
{%endblock%}       
{%block javascripts%}
{{parent()}}    
    <script type="text/javascript">
        $().ready(function(){
            $(".estrella").click(function(){
                $(".estrella").each(function(){
                    $(this).attr("class",'estrella');
                    $(this).html("☆");
                });
                $(this).attr("class",'estrella active');
                $(this).html("★");
                var id = $(this).data("id");
                $.getJSON('{{path("pordefecto_cliente")}}',{id:id}).done(function(data){
                });
            });
            $('.borrar').each(function(){
               $(this).click(function(ev){
                   ev.preventDefault();
                   $('#dataEliminar #cliente').html($(this).data('cliente'));
                   $('#borrar').attr('href','{{path('borrar_cliente')}}?id='+$(this).data('id'));
                   $('#eliminarCliente').modal('show');
               }); 
            });
        })        
    </script>    
{%endblock%}
{%block ajax%}    
            <table class="table table-bordered table-hover" id="clientes">
                <thead class="header">
                    <tr>
                        <th>Cliente</th>
                        <th>Teléfono</th>
                    </tr>
                </thead>
                <tbody>
                {%if estado==null%}
                        {%set estado='activo'%}        
                {% endif %}        
                {% for cliente in clientes%}
                     {%if cliente.estado=='activo'%}   
                        <tr onclick='seleccionarCliente({{cliente.id}},"{{cliente}}",{{cliente.direccion.ciudad.provincia.id}},{{cliente.direccion.ciudad.id}},"{{cliente.direccion.calle}}",{{cliente.direccion.numero}},"{{cliente.direccion.manzana}}","{{cliente.direccion.edificio}}","{{cliente.direccion.escalera}}","{{cliente.direccion.piso}}","{{cliente.direccion.departamento}}");' style='cursor:pointer;'>
                            <td>{{cliente}}</td>
                            <td>{{cliente.telefono}}</td>
                        </tr>
                     {% endif %}       
                {% endfor %}       
                    </tbody>
                </table>
{%endblock%}    