src/SisGG/FinalBundle/Entity/CuentaCorriente.php
<?php

namespace SisGG\FinalBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use SisGG\FinalBundle\Validator\Constraints as MyAssert;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * @ORM\Entity()
 * @ORM\HasLifecycleCallbacks()
 * @Gedmo\Loggable
 * @UniqueEntity(fields="cliente", message="Este cliente tiene una cuenta corriente asociada.")
 * @UniqueEntity(fields="numeroCuenta", message="Este número de cuenta tiene una cuenta corriente asociada.")
 */
class CuentaCorriente implements \Serializable {

    /**
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;
    
    /**
     * @ORM\Column(type="integer")
     */
    protected $numeroCuenta;

    /**
     * @ORM\Column(type="decimal", scale=2, nullable=true)
     */
    protected $saldo;
    
    /**
     * @ORM\Column(type="decimal", scale=2, nullable=true)
     */
    protected $maximo;
    
    /**
     * @ORM\Column(type="integer",nullable=true)
     */
    protected $plazoGeneracionRecibos;
    
    /**
     * @ORM\Column(type="integer",nullable=true)
     */
    protected $diasEntreAvisos;
    
    /**
     * @ORM\Column(type="string")
     */
    protected $estado;

    /**
     * @ORM\OneToMany(targetEntity="MovimientoCuentaCorriente",mappedBy="cuenta",cascade={"persist"})
     */
    private $movimientos;
    
    /**
     * @ORM\OneToOne(targetEntity="Cliente", inversedBy="cuenta")
     */
    protected $cliente;
    
    /**
     * @ORM\Column(type="datetime")
     */
    protected $fechaCreacion;
    
    /**
     * @ORM\Column(type="datetime",nullable=true)
     */
    protected $fechaEliminacion;

    public function __toString() {
        return $this->getNumero();
    }

    /**
     * @return string
     */
    public function serialize() {
        return serialize($this->id);
    }

    /**
     * @param string $data
     */
    public function unserialize($data) {
        $this->id = unserialize($data);
    }

    /**
     * @ORM\PrePersist
     */
    public function setCreatedValue() {
        $this->setEstado("activo");
        $this->setFechaCreacion(new \DateTime('now'));
    }
    
    /**
     * @return string
     */
    public function getNumero() {
        return str_pad($this->numeroCuenta, 8, 0, STR_PAD_LEFT);
    }
    
    /**
     * Constructor
     */
    public function __construct()
    {
        $this->movimientos = new \Doctrine\Common\Collections\ArrayCollection();
    }
    
    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set saldo
     *
     * @param string $saldo
     * @return CuentaCorriente
     */
    public function setSaldo($saldo)
    {
        $this->saldo = $saldo;
    
        return $this;
    }

    /**
     * Get saldo
     *
     * @return string 
     */
    public function getSaldo()
    {
        return $this->saldo;
    }

    /**
     * Add movimientos
     *
     * @param \SisGG\FinalBundle\Entity\MovimientoCuentaCorriente $movimientos
     * @return CuentaCorriente
     */
    public function addMovimiento(\SisGG\FinalBundle\Entity\MovimientoCuentaCorriente $movimientos)
    {
        $this->movimientos[] = $movimientos;
    
        return $this;
    }

    /**
     * Remove movimientos
     *
     * @param \SisGG\FinalBundle\Entity\MovimientoCuentaCorriente $movimientos
     */
    public function removeMovimiento(\SisGG\FinalBundle\Entity\MovimientoCuentaCorriente $movimientos)
    {
        $this->movimientos->removeElement($movimientos);
    }

    /**
     * Get movimientos
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getMovimientos()
    {
        return $this->movimientos;
    }

    /**
     * Set cliente
     *
     * @param \SisGG\FinalBundle\Entity\Cliente $cliente
     * @return CuentaCorriente
     */
    public function setCliente(\SisGG\FinalBundle\Entity\Cliente $cliente = null)
    {
        $this->cliente = $cliente;
    
        return $this;
    }

    /**
     * Get cliente
     *
     * @return \SisGG\FinalBundle\Entity\Cliente 
     */
    public function getCliente()
    {
        return $this->cliente;
    }

    /**
     * Set estado
     *
     * @param string $estado
     * @return CuentaCorriente
     */
    public function setEstado($estado)
    {
        $this->estado = $estado;
    
        return $this;
    }

    /**
     * Get estado
     *
     * @return string 
     */
    public function getEstado()
    {
        return $this->estado;
    }

    /**
     * Set fechaCreacion
     *
     * @param \DateTime $fechaCreacion
     * @return CuentaCorriente
     */
    public function setFechaCreacion($fechaCreacion)
    {
        $this->fechaCreacion = $fechaCreacion;
    
        return $this;
    }

    /**
     * Get fechaCreacion
     *
     * @return \DateTime 
     */
    public function getFechaCreacion()
    {
        return $this->fechaCreacion;
    }

    /**
     * Set fechaEliminacion
     *
     * @param \DateTime $fechaEliminacion
     * @return CuentaCorriente
     */
    public function setFechaEliminacion($fechaEliminacion)
    {
        $this->fechaEliminacion = $fechaEliminacion;
    
        return $this;
    }

    /**
     * Get fechaEliminacion
     *
     * @return \DateTime 
     */
    public function getFechaEliminacion()
    {
        return $this->fechaEliminacion;
    }

    /**
     * Set maximo
     *
     * @param string $maximo
     * @return CuentaCorriente
     */
    public function setMaximo($maximo)
    {
        $this->maximo = $maximo;
    
        return $this;
    }

    /**
     * Get maximo
     *
     * @return string 
     */
    public function getMaximo()
    {
        return $this->maximo;
    }

    /**
     * Set plazoGeneracionRecibos
     *
     * @param integer $plazoGeneracionRecibos
     * @return CuentaCorriente
     */
    public function setPlazoGeneracionRecibos($plazoGeneracionRecibos)
    {
        $this->plazoGeneracionRecibos = $plazoGeneracionRecibos;
    
        return $this;
    }

    /**
     * Get plazoGeneracionRecibos
     *
     * @return integer 
     */
    public function getPlazoGeneracionRecibos()
    {
        return $this->plazoGeneracionRecibos;
    }

    /**
     * Set diasEntreAvisos
     *
     * @param integer $diasEntreAvisos
     * @return CuentaCorriente
     */
    public function setDiasEntreAvisos($diasEntreAvisos)
    {
        $this->diasEntreAvisos = $diasEntreAvisos;
    
        return $this;
    }

    /**
     * Get diasEntreAvisos
     *
     * @return integer 
     */
    public function getDiasEntreAvisos()
    {
        return $this->diasEntreAvisos;
    }

    /**
     * Set numeroCuenta
     *
     * @param integer $numeroCuenta
     * @return CuentaCorriente
     */
    public function setNumeroCuenta($numeroCuenta)
    {
        $this->numeroCuenta = $numeroCuenta;
    
        return $this;
    }

    /**
     * Get numeroCuenta
     *
     * @return integer 
     */
    public function getNumeroCuenta()
    {
        return $this->numeroCuenta;
    }
}

src/SisGG/FinalBundle/Controller/CuentaCorrienteController.php
<?php

namespace SisGG\FinalBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use SisGG\FinalBundle\Entity\CuentaCorriente;
use SisGG\FinalBundle\Form\CuentaCorrienteType;
use Symfony\Component\HttpFoundation\Response;
use SisGG\FinalBundle\Form\MovimientoCuentaCorrienteHaberType;
use SisGG\FinalBundle\Entity\MovimientoCuentaCorrienteDebe;
use SisGG\FinalBundle\Entity\MovimientoCuentaCorrienteHaber;
use SisGG\FinalBundle\Entity\Recibo;
use SisGG\FinalBundle\Form\ReciboType;
//use Ps\PdfBundle\Annotation\Pdf;
use SisGG\FinalBundle\Entity\EnLetras;
/**
 * Description of ClienteController
 *
 * @author martin
 */
class CuentaCorrienteController extends Controller {

    public function cuentasCorrientesAction(){
        $gestor = $this->get("gestor_autenticacion");
        if (!$gestor->isGranted($this->getUser(),  \SisGG\FinalBundle\Autenticacion\GestorAutenticacion::CLIENTE_LISTAR)){
            throw new \Symfony\Component\Security\Core\Exception\AccessDeniedException();
        }
        $repositorio = $this->getDoctrine()->getRepository('SisGGFinalBundle:CuentaCorriente');
        $cuentasCorrientes = $repositorio->findAll();
        $estado = $this->getRequest()->get('estado');
        return $this->render('SisGGFinalBundle:CuentaCorriente:cuentasCorrientes.html.twig', array('form' => null, "cuentasCorrientes" => $cuentasCorrientes,'gestor_autenticacion'=>$gestor,'estado'=>$estado));
    }
    
    public function nuevoCuentaCorrienteAction(){
        $gestor = $this->get("gestor_autenticacion");
        if (!$gestor->isGranted($this->getUser(),  \SisGG\FinalBundle\Autenticacion\GestorAutenticacion::CAJA_APERTURA_Y_CIERRRE)){
            throw new \Symfony\Component\Security\Core\Exception\AccessDeniedException();
        }
        $unCuentaCorriente = $this->get("gestor_cuenta_corriente")->nuevaCuentaCorriente($this->getRequest()->get('id'));
        $em = $this->getDoctrine()->getEntityManager();
        $form = $this->createForm(new CuentaCorrienteType(),$unCuentaCorriente);
        if ($this->getRequest()->getMethod() === 'POST') {
        $form->bindRequest($this->getRequest());
                if ($form->isValid()) {
                    $em = $this->getDoctrine()->getEntityManager();
                    $unCuentaCorriente->setEstado('activo');
                    $em->persist($unCuentaCorriente);
                    $em->flush();
                    return $this->redirect($this->generateUrl("cuentas_corrientes"));
                }
            }
        return $this->render('SisGGFinalBundle:CuentaCorriente:nuevoCuentaCorriente.html.twig',array('form' => $form->createView(),'gestor_autenticacion'=>$gestor));  
    }
    
    public function detalleCuentaCorrienteAction(){
        $gestor = $this->get("gestor_autenticacion");
        if (!$gestor->isGranted($this->getUser(),  \SisGG\FinalBundle\Autenticacion\GestorAutenticacion::CAJA_APERTURA_Y_CIERRRE)){
            throw new \Symfony\Component\Security\Core\Exception\AccessDeniedException();
        }
        $unaCuentaCorriente = $this->get("gestor_cuenta_corriente")->getCuentaCorriente($this->getRequest()->get('id'));
        return $this->render('SisGGFinalBundle:CuentaCorriente:detalleCuentaCorriente.html.twig',array('form' => null,'gestor_autenticacion'=>$gestor,'unaCuentaCorriente'=>$unaCuentaCorriente,'id'=>$this->getRequest()->get('id')));  
    }
    
    public function registrarCobroCuentaCorrienteAction(){
        $gestor = $this->get("gestor_autenticacion");
        if (!$gestor->isGranted($this->getUser(),  \SisGG\FinalBundle\Autenticacion\GestorAutenticacion::CAJA_APERTURA_Y_CIERRRE)){
            throw new \Symfony\Component\Security\Core\Exception\AccessDeniedException();
        }
        /* @var $unRecibo Recibo*/
        $unRecibo = $this->get("gestor_cuenta_corriente")->nuevoRecibo($this->getRequest()->get('id'));
        $form = $this->createForm(new ReciboType(),$unRecibo);
        if ($this->getRequest()->getMethod() === 'POST') {
        $form->bindRequest($this->getRequest());
                if ($form->isValid()) {
                    $this->get("gestor_cuenta_corriente")->guardarRecibo($unRecibo,$this->getUser());
                    return $this->redirect($this->generateUrl("cuentas_corrientes"));
                }
            }
        return $this->render('SisGGFinalBundle:CuentaCorriente:registrarCobro.html.twig',array('form' => $form->createView(),'gestor_autenticacion'=>$gestor,'id'=>$this->getRequest()->get("id"))); 
    }
    
    public function detalleCobroAction(){
        $gestor = $this->get("gestor_autenticacion");
        if (!$gestor->isGranted($this->getUser(),  \SisGG\FinalBundle\Autenticacion\GestorAutenticacion::CAJA_APERTURA_Y_CIERRRE)){
            throw new \Symfony\Component\Security\Core\Exception\AccessDeniedException();
        }
        /* @var $unRecibo Recibo*/
        $unRecibo = $this->getDoctrine()->getRepository("SisGGFinalBundle:Recibo")->find($this->getRequest()->get('id'));
        return $this->render('SisGGFinalBundle:CuentaCorriente:detalleCobro.html.twig',array('form' => null,'gestor_autenticacion'=>$gestor,'unRecibo'=>$unRecibo)); 
    }
    
    public function editarCuentaCorrienteAction(){
        $gestor = $this->get("gestor_autenticacion");
        if (!$gestor->isGranted($this->getUser(),  \SisGG\FinalBundle\Autenticacion\GestorAutenticacion::CAJA_APERTURA_Y_CIERRRE)){
            throw new \Symfony\Component\Security\Core\Exception\AccessDeniedException();
        }
        $unCuentaCorriente = $this->getDoctrine()->getRepository("SisGGFinalBundle:CuentaCorriente")->find($this->getRequest()->get("id"));
        $em = $this->getDoctrine()->getEntityManager();
        $form = $this->createForm(new CuentaCorrienteType(),$unCuentaCorriente);
        if ($this->getRequest()->getMethod() === 'POST') {
        $form->bindRequest($this->getRequest());
                if ($form->isValid()) {
                    $em = $this->getDoctrine()->getEntityManager();
                    $em->flush();
                    return $this->redirect($this->generateUrl("cuentas_corrientes"));
                }
            }
        return $this->render('SisGGFinalBundle:CuentaCorriente:editarCuentaCorriente.html.twig',array('form' => $form->createView(),'gestor_autenticacion'=>$gestor,'id'=>$this->getRequest()->get("id")));  
    }
    
    public function activarCuentaCorrienteAction() {
        $gestor = $this->get("gestor_autenticacion");
        if (!$gestor->isGranted($this->getUser(),  \SisGG\FinalBundle\Autenticacion\GestorAutenticacion::CLIENTE_BORRAR)){
            throw new \Symfony\Component\Security\Core\Exception\AccessDeniedException();
        }
        $repositorio = $this->getDoctrine()->getRepository('SisGGFinalBundle:CuentaCorriente');
        $cliente = $repositorio->find($this->getRequest()->get('id'));
        $cliente->setEstado('activo');
        $this->getDoctrine()->getEntityManager()->flush($cliente);
        return $this->redirect($this->generateUrl("cuentas_corrientes"));
    }
    
    public function borrarCuentaCorrienteAction() {
        $gestor = $this->get("gestor_autenticacion");
        if (!$gestor->isGranted($this->getUser(),  \SisGG\FinalBundle\Autenticacion\GestorAutenticacion::CLIENTE_BORRAR)){
            throw new \Symfony\Component\Security\Core\Exception\AccessDeniedException();
        }
        $repositorio = $this->getDoctrine()->getRepository('SisGGFinalBundle:CuentaCorriente');
        $cliente = $repositorio->find($this->getRequest()->get('id'));
        $cliente->setEstado('inactivo');
        $this->getDoctrine()->getEntityManager()->flush($cliente);
        return $this->redirect($this->generateUrl("cuentas_corrientes"));
    }
    
    public function cuentaCorrienteAction(){
        $retorno = null;
        /*@var $unaCuentaCorriente CuentaCorriente*/
        $unaCuentaCorriente = $this->get("gestor_cuenta_corriente")->getCuentaCorrienteCliente($this->getRequest()->get('id'));
        if ( $unaCuentaCorriente != null){
            $retorno = array('existe'=>true,"maximo"=>$unaCuentaCorriente->getMaximo());
        }else{
            $retorno = array('existe'=>false);
        }
        return new Response(json_encode($retorno));
    }
    
//    /**
//     * @Pdf()
//     */
//    public function impListaCuentasCorrientesAction() {
//        $lista = explode(",", $this->getRequest()->get('ids'));
//        $info = $this->getRequest()->get('info');
//        $array = null;
//        foreach ($lista as $id) {
//            if ($id != null)
//                $array[] = $this->getDoctrine()->getRepository('SisGGFinalBundle:CuentaCorriente')->find($id);
//        }
//        $format = $this->get('request')->get('_format');
//        $parameters = array('form' => null, 'items' => $array, 'info' => $info, 'empresa' => $this->getEmpresa());
//        return $this->render('SisGGFinalBundle:CuentaCorriente:imp_lista.' . $format . '.twig', $parameters);
//    }
//
//    /**
//     * @Pdf()
//     */
//    public function impCuentaCorrienteAction(){
//        $gestor = $this->get("gestor_autenticacion");
//        if (!$gestor->isGranted($this->getUser(),  \SisGG\FinalBundle\Autenticacion\GestorAutenticacion::CAJA_APERTURA_Y_CIERRRE)){
//            throw new \Symfony\Component\Security\Core\Exception\AccessDeniedException();
//        }
//        $format = $this->get('request')->get('_format');
//        $unaCuentaCorriente = $this->get("gestor_cuenta_corriente")->getCuentaCorriente($this->getRequest()->get('id'));
//        return $this->render('SisGGFinalBundle:CuentaCorriente:imp_cuenta_corriente.' . $format . '.twig',array('form' => null,'gestor_autenticacion'=>$gestor, 'empresa' => $this->getEmpresa(),'unaCuentaCorriente'=>$unaCuentaCorriente,'id'=>$this->getRequest()->get('id')));
//    }
//
//    /**
//     * @Pdf()
//     */
//    public function impReciboAction() {

src/SisGG/FinalBundle/Resources/views/CuentaCorriente/detalleCobro.html.twig
{% extends app.request.isXmlHttpRequest ? "::ajax.html.twig" : "SisGGFinalBundle:Cajero:cajero.html.twig" %}
{%if form%}{% form_theme form "SisGGFinalBundle:Form:fields.html.twig" %}{%endif%}
{%block ruta%}
<li>
    <a href="#">Inicio</a> <span class="divider">/</span>
</li>
<li>
    <a href="#">Cuenta Corriente</a> <span class="divider">/</span>
</li>
<li>
    <a href="#">Detalles cobro</a>
</li>
{%endblock%}
{% block content %}
<div class="row-fluid sortable">
    <div class="box span12">
        <div class="box-content">
            <legend>Detalles de cobro
                <div class="btn-group" style='float:right;'>
                    <a href="{{path('imp_recibo')}}?id={{unRecibo.id}}&_format=pdf" title="Imprimir" class='btn'><i class='fa-icon-print'></i></a>
                </div>
            </legend>
            <form class="form-horizontal" method="post">
                <fieldset id="formNuevoCondicionIva">
                    <div class="tab-content">
                        <div class="tab-pane active" id="general">
                            <div class="span6">
                                <div class='control-group'>
                                    <label class='control-label'>Fecha y hora de Emisión</label>
                                    <div class='controls'>
                                        <input class='span9' type='text' disabled="disabled" value='{{unRecibo.fecha|date('d/m/Y g:i a')}}'/>
                                    </div>    
                                </div>
                                <div class='control-group'>
                                    <label class='control-label'>Número de Recibo</label>
                                    <div class='controls'>
                                        <input class='span9' type='text' disabled="disabled" value='{{unRecibo.numero}}'/>
                                    </div>    
                                </div>
                                <div class='control-group'>
                                    <label class='control-label'>Cliente</label>
                                    <div class='controls'>
                                        <input class='span9' type='text' disabled="disabled" value='{{unRecibo.cliente}}'/>
                                    </div>    
                                </div>
                                <div class='control-group'>
                                    <label class='control-label'>Total entregado</label>
                                    <div class='controls'>
                                        <input class='span9' style='text-align: right' type='text' disabled="disabled" value='{{unRecibo.total|number_format(2,'.','')}}'/>
                                    </div>    
                                </div>    
                            </div>
                        </div>
                        </div>    
                        </div>       
                    </fieldset>
                </form>
            </div>
        </div><!--/span-->
    </div><!--/row-->
    <hr>
{% endblock %}
{%block javascripts%}
{{parent()}}
    <script type="text/javascript">
            $().ready(function() {
                $("#myTab a").each(function() {
                    $(this).tab("show");
                });
                $("#myTab a:first").each(function() {
                    $(this).tab("show");
                });
            });
            </script>    
{%endblock%}
{%block modal%}
{{parent()}}
        <div class="modal hide fade" id="busqueda">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">×</button>
                <h3>Buscar...</h3>
            </div>
            <div id="dataBusqueda" class="modal-body">
                <p>Here settings can be configured...</p>
            </div>
            <div class="modal-footer">
                <a href="#" class="btn" data-dismiss="modal">Cancelar</a>
            </div>
        </div>
{% endblock %}
{% block ajax %}
{% endblock %}

src/SisGG/FinalBundle/Resources/views/CuentaCorriente/detalleCuentaCorriente.html.twig
{% extends app.request.isXmlHttpRequest ? "::ajax.html.twig" : "SisGGFinalBundle:Cajero:cajero.html.twig" %}
{%if form%}{% form_theme form "SisGGFinalBundle:Form:fields.html.twig" %}{%endif%}
{%block ruta%}
<li>
    <a href="#">Inicio</a> <span class="divider">/</span>
</li>
<li>
    <a href="#">Cuenta Corriente</a> <span class="divider">/</span>
</li>
<li>
    <a href="#">Detalles de cuenta Corriente</a>
</li>
{%endblock%}
{% block content %}
<div class="row-fluid sortable">
    <div class="box span12">
        <div class="box-content">
            <legend>Detalles de cuenta Corriente
                <div class="btn-group" style='float:right;'>
                    <a title="Editar cuenta corriente" href="{{path('editar_cuenta_corriente')}}?id={{unaCuentaCorriente.id}}" class="btn"><i class=" fa-icon-edit"></i></a>
                    <a class='btn' rel="tooltip" title="Imprimir" href="{{path('imp_cuenta_corriente')}}?id={{unaCuentaCorriente.id}}&_format=pdf"><i class="icon-print"></i></a>
                </div>
                <small>
                    <ul class="nav nav-pills" id="myTab">
                        <li class="active"><a href="#general">General</a></li>
                        <li><a href="#movimientos">Movimientos</a></li>
                    </ul>
                </small>
            </legend>
            <form class="form-horizontal" method="post">
                <fieldset id="formNuevoCondicionIva">
                    <div class="tab-content">
                        <div class="tab-pane active" id="general">
                            <div class="span6">
                                <div class='control-group'>
                                    <label class='control-label'>Número de Cuenta</label>
                                    <div class='controls'>
                                        <input class='span9' type='text' disabled="disabled" value='{{unaCuentaCorriente.numero}}'/>
                                    </div>    
                                </div>
                                <div class='control-group'>
                                    <label class='control-label'>Cliente</label>
                                    <div class='controls'>
                                        <input class='span9' type='text' disabled="disabled" value='{{unaCuentaCorriente.cliente}}'/>
                                    </div>    
                                </div>
                                <div class='control-group'>
                                    <label class='control-label'>Saldo Actual</label>
                                    <div class='controls'>
                                        <input class='span9' style='text-align: right' type='text' disabled="disabled" value='{{unaCuentaCorriente.saldo|number_format(2,'.','')}}'/>
                                    </div>    
                                </div>    
                            </div>
                                <div class="span6">
                                
                                    </div>
                        </div>
                            <div class="tab-pane active" id="movimientos">
                            <table class="table table-striped table-bordered" id="movimientos">
                                <thead class="header">
                                    <tr>
                                        <th>Fecha y hora</th>
                                        <th>Comprobante</th>
                                        <th>Debe</th>
                                        <th>Haber</th>
                                        <th width='30px'>Acciones</th>
                                    </tr>
                                </thead>
                                <tbody>     
                                {% for movimiento in unaCuentaCorriente.movimientos%}  
                                        <tr>
                                            <td>{{movimiento.fecha|date('d/m/Y g:i a')}}</td>
                                            {%if movimiento.isHaber%}
                                                <td>{{movimiento.unRecibo}}</td>
                                                <td style='text-align: center'>---</td>
                                                <td style='text-align: right'>{{movimiento.importe}}</td>
                                            {%endif%}
                                            {%if movimiento.isDebe%}
                                                <td>{{movimiento.unaVenta}}</td>
                                                <td style='text-align: right'>{{movimiento.importe}}</td>
                                                <td style='text-align: center'>---</td>
                                            {%endif%}
                                            <td style='text-align: center'>
                                            {%if movimiento.isHaber%}
                                                <a rel="tooltip" title="Detalles Cobro" href="{{path('detalle_cobro')}}?id={{movimiento.unRecibo.id}}"><i class="fa-icon-list-alt"></i></a>    
                                            {%endif%}
                                            {%if movimiento.isDebe%}
                                                <a rel="tooltip" title="Detalles Venta" href="{{path('detalles_venta')}}?id={{movimiento.unaVenta.id}}"><i class="fa-icon-list-alt"></i></a>
                                            {%endif%}
                                            </td>
                                        </tr>    
                                {% endfor %}       
                                    </tbody>
                                </table>
                            </div>
                        </div>    
                        </div>       
                    </fieldset>
                </form>
            </div>
        </div><!--/span-->
    </div><!--/row-->
    <hr>
{% endblock %}
{%block javascripts%}
{{parent()}}
    <script type="text/javascript">
            $().ready(function() {
                $("#myTab a").each(function() {
                    $(this).tab("show");
                });
                $("#myTab a:first").each(function() {
                    $(this).tab("show");
                });
            });
            </script>    
{%endblock%}
{%block modal%}
{{parent()}}
        <div class="modal hide fade" id="busqueda">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">×</button>
                <h3>Buscar...</h3>
            </div>
            <div id="dataBusqueda" class="modal-body">
                <p>Here settings can be configured...</p>
            </div>
            <div class="modal-footer">
                <a href="#" class="btn" data-dismiss="modal">Cancelar</a>
            </div>
        </div>
{% endblock %}
{% block ajax %}
{% endblock %}

src/SisGG/FinalBundle/Resources/views/CuentaCorriente/imp_recibo.pdf.twig
{% extends "::imprimir.html.twig" %}
{%block tipo_hoja%}
a4{%endblock %}
{%block orientacion_hoja%}
{%endblock%}

{# landscapehorizontal#}
{%block cabecera%}
{{parent()}}

{%endblock%}   
{%block titulo_reporte%}Recibo{%endblock titulo_reporte%}
{%block contenido%}
{{parent()}}
<h1 style='text-align: center;'>Recibo</h1>
<div font-size="10" font-type="helvetica" width='100%'>
    <p></p>    
    <table width='100%'>
        <tr>
            <td text-align="left"  width='100%' border.type="none">
                <div  width='100%'>
                </div>
                <div  width='100%'>
                    <b>Cliente: </b> {{unRecibo.serie}}
                </div>    
                <div  width='100%'>
                    <b>Cliente: </b> {{unRecibo.cliente}}
                </div>
                <div  width='100%'>
                    <b>Saldo: </b> {{unRecibo.total|number_format(2,'.','')}}
                </div>    
            </td>
        </tr>
    </table>
    <p></p>
        
        </div>
{%endblock%}